[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"
authors = ["BRAVO68WEB"]
default-run = "aoc-2024"

[dependencies]

[profile.release]
lto = "fat"
codegen-units = 1

[[bin]]
name = "day01"
path = "src/d1.rs"